name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools-version: 33.0.2
      - run: |
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: wisdom-timetable-apk
          path: app/build/outputs/apk/release/app-release.apk
